# Generated by Django 6.1.1 on 2026-09-24 23:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('commune', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('bank_transfer', 'Transferencia bancaria'), ('check', 'Cheque'), ('debit_card', 'Tarjeta de débito'), ('credit_card', 'Tarjeta de crédito'), ('promissory_notes', 'Letras de cambio')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='companies.company')),
            ],
        ),
    ]
