# Generated by Django 6.1.1 on 2026-09-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='commune',
            field=models.CharField(choices=[('Arica', 'Arica'), ('Iquique', 'Iquique'), ('Antofagasta', 'Antofagasta'), ('Calama', 'Calama'), ('Copiapó', 'Copiapó'), ('La Serena', 'La Serena'), ('Coquimbo', 'Coquimbo'), ('Ovalle', 'Ovalle'), ('Valparaíso', 'Valparaíso'), ('Viña del Mar', 'Viña del Mar'), ('Quilpué', 'Quilpué'), ('San Antonio', 'San Antonio'), ('Santiago', 'Santiago'), ('Puente Alto', 'Puente Alto'), ('Maipú', 'Maipú'), ('La Florida', 'La Florida'), ('Las Condes', 'Las Condes'), ('Ñuñoa', 'Ñuñoa'), ('Peñalolén', 'Peñalolén'), ('Conchalí', 'Conchalí'), ('Quilicura', 'Quilicura'), ('Lampa', 'Lampa'), ('Colina', 'Colina'), ('Buin', 'Buin'), ('Pudahuel', 'Pudahuel'), ('Talagante', 'Talagante'), ('Machalí', 'Machalí'), ('Rancagua', 'Rancagua'), ('San Fernando', 'San Fernando'), ('Curicó', 'Curicó'), ('Talca', 'Talca'), ('Linares', 'Linares'), ('Cauquenes', 'Cauquenes'), ('Concepción', 'Concepción'), ('Talcahuano', 'Talcahuano'), ('Chillán', 'Chillán'), ('Los Ángeles', 'Los Ángeles'), ('Temuco', 'Temuco'), ('Villarrica', 'Villarrica'), ('Valdivia', 'Valdivia'), ('Osorno', 'Osorno'), ('Puerto Montt', 'Puerto Montt'), ('Castro', 'Castro'), ('Coyhaique', 'Coyhaique'), ('Punta Arenas', 'Punta Arenas')], max_length=100),
        ),
    ]
