# Generated by Django 6.1.1 on 2026-09-25 00:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('product', 'Producto'), ('consumable', 'Consumible'), ('service', 'Servicio')], max_length=20)),
                ('category', models.CharField(choices=[('solar_panel', 'Panel solar'), ('inverter', 'Inversor'), ('battery', 'Batería'), ('mounting_structure', 'Estructura de montaje'), ('cable', 'Cable'), ('connector', 'Conector'), ('installation', 'Instalación'), ('engineering', 'Ingeniería'), ('other', 'Otro')], max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('model', models.CharField(blank=True, max_length=150)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(choices=[('unit', 'Unidad'), ('meter', 'Metro'), ('square_meter', 'Metro cuadrado'), ('hour', 'Hora'), ('day', 'Día'), ('service', 'Servicio')], default='unit', max_length=20)),
                ('stock_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('technical_specs', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='companies.company')),
            ],
        ),
    ]
